In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset=pd.read_excel('C:/Users/user/Desktop/data set/Store-Sales-Dataset.xlsx')
dataset.head()

S/N  Order ID Order Date Order Priority  Order Quantity    Sales  \
0    1     13729 2009-01-01  Not Specified               9   872.48   
1    2     28774 2009-01-01           High              32   180.36   
2    3     37537 2009-01-02            Low              32  4902.38   
3    4     37537 2009-01-02            Low              43  4083.19   
4    5     37537 2009-01-02            Low               4  1239.06   

   Unit Price       Ship Mode  Shipping Cost  Total Cost          Province  \
0   96.942222     Express Air          35.00      907.48            Quebec   
1    5.636250     Regular Air           4.69      185.05           Ontario   
2  153.199375     Regular Air           7.07     4909.45  British Columbia   
3   94.957907  Delivery Truck          45.00     4128.19  British Columbia   
4  309.765000  Delivery Truck          48.80     1287.86  British Columbia   

  Customer Segment Product Category    Product Sub-Category Product Container  \
0      Home Office  Office Supplies  Storage & Organization         Large Box   
1   Small Business  Office Supplies  Storage & Organization         Small Box   
2        Corporate  Office Supplies  Storage & Organization         Small Box   
3        Corporate        Furniture      Chairs & Chairmats        Jumbo Drum   
4        Corporate        Furniture      Chairs & Chairmats        Jumbo Drum   

   Ship Date  
0 2009-01-03  
1 2009-01-02  
2 2009-01-09  
3 2009-01-04  
4 2009-01-02

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   S/N                   8399 non-null   int64         
 1   Order ID              8399 non-null   int64         
 2   Order Date            8399 non-null   datetime64[ns]
 3   Order Priority        8399 non-null   object        
 4   Order Quantity        8399 non-null   int64         
 5   Sales                 8399 non-null   float64       
 6   Unit Price            8399 non-null   float64       
 7   Ship Mode             8399 non-null   object        
 8   Shipping Cost         8399 non-null   float64       
 9   Total Cost            8399 non-null   float64       
 10  Province              8399 non-null   object        
 11  Customer Segment      8399 non-null   object        
 12  Product Category      8399 non-null   object        
 13  Product Sub-Catego

In [5]:
x= dataset[['Shipping Cost','Total Cost']]

In [6]:
from sklearn.cluster import DBSCAN

In [7]:
db=DBSCAN(eps=3,min_samples=10)

In [8]:
model= db.fit(x)

In [9]:
labels=model.labels_

In [10]:
samples_cores=np.zeros_like(labels,dtype=bool)

In [11]:
samples_cores

array([False, False, False, ..., False, False, False])

In [12]:
db.core_sample_indices_

array([   1,    6,    7, ..., 8395, 8397, 8398], dtype=int64)

In [13]:
n_cluster=len(set(labels))-(1 if -1 in labels else 0)

In [14]:
from sklearn import metrics

In [15]:
print(metrics.silhouette_score(x,labels))

-0.02172613864485228


In [16]:
model.labels_

array([-1,  0, -1, ..., -1,  0,  0], dtype=int64)